apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: aksdotnetcoder
spec:
  template:
    metadata:
      labels:
        app: aksdotnet
    spec:
      containers:
      - name: aksdotnet
        image: "acrname.azurecr.io/aksdotnetcoder:latest"
        ports:
        - containerPort: 80 
---
apiVersion: v1
kind: Service
metadata:
  name: aksdotnet
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: aksdotnet
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: aksdotnet
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: aksdotnetcoder.dns-zone.aksapp.io
    http:
      paths:
      - backend:
          serviceName: aksdotnet
          servicePort: 80
        path: /